# This file is part of agora-dev-box.
# Copyright (C) 2014-2016  Agora Voting SL <agora@agoravoting.com>

# agora-dev-box is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License.

# agora-dev-box  is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with agora-dev-box.  If not, see <http://www.gnu.org/licenses/>.

---
- hosts: all

  tasks:
    - include_vars: config.yml
    - include_vars: repos.yml

    - include: java.yml
    - include: packages.yml
    - include: system.yml
    - include: sudoers/main.yml
    - include: agora-tools/main.yml
    - include: eorchestra/main.yml
    #- include: agora-elections/main.yml
    #- include: authapi/main.yml
    #- include: sentry/main.yml
    #- include: agora-gui/main.yml
    #- include: oneserver/main.yml
    - include: agora-verifier/main.yml
    #- include: halb/main.yml
    - include: postgres_backups.yml
